language: node_js
sudo: false
cache: yarn
node_js:
- '6.1'
script: yarn test && yarn build
deploy:
  provider: npm
  email: hex22a@gmail.com
  api_key:
    secure: YQHM52J8T48ZHQ+Q5iq0Xi/veL3bx5i3Fe1sfhKgiv0YjHzxPmXL3gxQReLg6ZJMzyP9GlpnWoeaa03Jv5uP0gI+Obn/6Qba8YAmlvdme8S4evmyWJfA2sTVnduqIUtV7Krk05uqZ15X1NQad08YuAY6Fpj+fP9ZzQSOxEL41WHuHZg8NzfQDkGgQoearIA+OpxOg4kCll7zMecn4H6fljjn+bHAStW1PCPJC05MU9cPJhj1d1mHwlzkLbLUdZRrmblfgrIkZNt6H/dADK0nJgW3a9fm9n/nXFsGE1Z9atDP+4w4CTF29fiR7VNAlrV92ikg9OYE1AMEQo1UHgrg1k7XLBDlVMAZ9dV1EmbL9056Niois2TEdKVPpX6mnyGbKQXHT1IFGqfbXiPXtoAIGEg3S29zwiFsffnsslUrCVr3WnhQwTcNdbenCIXuWbF9mNxsa41ko5f2Qwu0cULMH+i/7EeK89d/mbExluu50RQTTIeiDWfDrsayJRlURpd3GdP7NDf8nbfXC8dTzlho25bpiJgw1ZUIq5lWINqpUBjdzrR+qKnbWjqQFg/YYkL7uQiNJmK1pzSBBTtblzxQvCmY8R+6+4ac0Mbwasj++dPYPkKJdYrkej+RTQ6ZgvkWeDg/edn49sSYY4w3lcF2jCO5Gvhwvy6catby6P2SaN4=
  on:
    tags: true
    repo: hex22a/jwt-redux-devtools
